In [1]:
!mamba install pandas

mambajs 0.21.1

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 0.7992999999999302 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.3    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.2   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [2]:
# Loading panda library:
import pandas as pd

In [3]:
#Importing Raw Data:

In [4]:
jan2026 = pd.read_csv('202601-divvy-tripdata.csv')
feb2026 = pd.read_csv('202602-divvy-tripdata.csv')
mar2026 = pd.read_csv('202603-divvy-tripdata.csv')

In [5]:
#Merging all Datasets:

In [6]:
dataframe = [jan2026, feb2026, mar2026]
df_comp = pd.concat(dataframe)

In [7]:
# Checking the structure of all dataset files:
# All tables should have the same structure to complete the merging step successfully. Check showed that all 
# 12 datasets have a countable number of rows and 12 columns with the same index names.

In [8]:
# Checking rows columns and its names in datasets:
for _ in dataframe:
    print(_.shape)
    print(_.columns)
# Raw Datasets contain 12 same columns. Therefore, tables are consistent.

(137787, 13)
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')
(201450, 13)
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')
(317037, 13)
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

In [9]:
# Confirms twelve columns with the same vars. Total rows for Q1 = 656,274

In [10]:
# Places Ride_ID index at the beginning of the table:
df_comp = df_comp.reset_index(level=0)

In [11]:
# Checks Data Types:
df_comp.dtypes

index                   int64
ride_id                   str
rideable_type             str
started_at                str
ended_at                  str
start_station_name        str
start_station_id          str
end_station_name          str
end_station_id            str
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual             str
dtype: object

In [12]:
# Changing data types to datetype format:

# Columns "started_at" and "ended_at" should be in datetype format:
df_comp['started_at'] = pd.to_datetime(df_comp['started_at'])
# Check the first cell:
df_comp['started_at'][0]

Timestamp('2026-01-31 09:13:09.018000')

In [13]:
df_comp['ended_at'] = pd.to_datetime(df_comp['ended_at'])
# Check the first cell:
df_comp['ended_at'][0]

Timestamp('2026-01-31 09:28:10.302000')

In [14]:
##  Through dataset errors for typos or misspellings

In [15]:
df_comp.rideable_type.unique()
# There are 2 distinct bike types used in Q1 of 2026. Returns True in linked study.

<StringArray>
['classic_bike', 'electric_bike']
Length: 2, dtype: str

In [16]:
df_comp.member_casual.unique()
# There are 2 distinct member types used in Q1 of 2026.

<StringArray>
['member', 'casual']
Length: 2, dtype: str

In [17]:
df_comp.start_station_id.value_counts()

start_station_id
CHI00498    4886
CHI02181    3947
CHI01772    3908
CHI00551    3862
CHI01747    3828
            ...
CHI00827       1
CHI00947       1
CHI01431       1
CHI01099       1
CHI02211       1
Name: count, Length: 1417, dtype: int64

In [18]:
df_comp.start_station_name.value_counts()

start_station_name
Canal St & Madison St                            4886
Kingsbury St & Kinzie St 2                       3947
State St & Chicago Ave                           3908
University Ave & 57th St                         3862
Navy Pier                                        3828
                                                 ...
Indiana Ave & 133rd St Public Rack                  1
Public Rack - California Ave & Touhy Ave - NW       1
Public Rack - Pulaski Rd & Polk St                  1
Public Rack - Damen Ave & 47th St                   1
Harlem Ave & Roscoe St                              1
Name: count, Length: 1416, dtype: int64

In [19]:
df_comp.end_station_id.value_counts()
# Varying station names with IDs that occur once.
# ASK how error or new deleted stations affected this, and observe

end_station_id
CHI00498    4925
CHI01772    3960
CHI01091    3881
CHI02181    3877
CHI00551    3812
            ...
CHI01520       1
CHI00894       1
CHI01201       1
CHI00950       1
CHI01306       1
Name: count, Length: 1433, dtype: int64

In [20]:
df_comp.end_station_name.value_counts()

end_station_name
Canal St & Madison St                            4925
State St & Chicago Ave                           3960
Clinton St & Jackson Blvd                        3881
Kingsbury St & Kinzie St 2                       3877
University Ave & 57th St                         3812
                                                 ...
Public Rack - Kedvale Ave & 26th St                 1
Public Rack - California Ave & Devon Ave - NE       1
Public Rack - Austin Blvd & North Ave               1
Public Rack - California Ave & Devon Ave - NW       1
Public Rack - Halsted St & 95th St - SE             1
Name: count, Length: 1433, dtype: int64

In [21]:
#check back later for proof

In [22]:
# Checks for length of Ride IDs and looking for it duplicates:
df_comp['ride_id'].map(len).unique()

array([16], dtype=int64)

In [23]:
# Searches for duplicates in Ride Id:
df_comp.duplicated(subset=['ride_id']).value_counts()
# Returns with no duplicates

False    656274
Name: count, dtype: int64

In [25]:
# Checking for empty cells, null values:
for column in df_comp.columns:
    print(df_comp[column].isnull().value_counts())
# 114396 rows with empty cells or null values in start station description columns
# start_station_id inconsistent length and format

# 125215 rows with empty cells or null values in start station description columns
# end_station_id inconsistent length and format

# 125215 rows where both start and end station is not given

# 608 rows with empty cells or null values in end coordinates columns

index
False    656274
Name: count, dtype: int64
ride_id
False    656274
Name: count, dtype: int64
rideable_type
False    656274
Name: count, dtype: int64
started_at
False    656274
Name: count, dtype: int64
ended_at
False    656274
Name: count, dtype: int64
start_station_name
False    541878
True     114396
Name: count, dtype: int64
start_station_id
False    541878
True     114396
Name: count, dtype: int64
end_station_name
False    531059
True     125215
Name: count, dtype: int64
end_station_id
False    531059
True     125215
Name: count, dtype: int64
start_lat
False    656274
Name: count, dtype: int64
start_lng
False    656274
Name: count, dtype: int64
end_lat
False    655666
True        608
Name: count, dtype: int64
end_lng
False    655666
True        608
Name: count, dtype: int64
member_casual
False    656274
Name: count, dtype: int64

In [ ]:
#Removing incompletes, and checks number of deleted rows:

In [27]:
# Deleting rows with missing data:
no_nan_data = df_comp.dropna()
no_nan_data.shape
#The dataset without NAN values contains 466640 rows which is 71% of the whole set

(466640, 14)

In [ ]:
#Looking for unwanted data – test data:
# There were few instances with “TEST” in previous iterations. The start and end
# station id’s columns. All of them should not be
# considered. After deletion there were 466640_ rows left (about 71%_ of the whole dataset).
#

In [28]:
# Searching for the unwanted data - test data.
# Context: TEST found in one of the start stations id's "Hubbard Bike-checking (LBS-WH-TEST)"
no_nan_data['start_station_id'].str.contains('TEST').value_counts()
# 1207 test rides found in start station id's. All should not be considered.

start_station_id
False    466640
Name: count, dtype: int64

In [29]:
no_nan_data['start_station_name'].str.contains('TEST').value_counts()
# No test rides found in start station names.

start_station_name
False    466640
Name: count, dtype: int64

In [30]:
# Deleting test rides:
no_test_start_data = no_nan_data[no_nan_data['start_station_id'].str.contains(
    'TEST') != True]

In [31]:

no_test_start_data['end_station_name'].str.contains('TEST').value_counts()
# No test rides found in end station names.

end_station_name
False    466640
Name: count, dtype: int64

In [33]:
# Deleting test rides:
no_nan_no_test_data = no_test_start_data[no_test_start_data['end_station_id'].str.contains(
    'TEST') != True]
# 466640 rows left

In [ ]:
# Preparing the data:
# Adding new column to calculate ride time:

In [34]:
# Dataframe with no test rides and no NaN values:
no_nan_no_test_data.head(5)

,index,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0,FD0EB1D32AF0D47E,classic_bike,2026-01-31 09:13:09.018,2026-01-31 09:28:10.302,Central St & Girard Ave,CHI02042,Dodge Ave & Church St,CHI00741,42.064313,-87.686152,42.048308,-87.698224,member
1,1,FB27405C3F8C824F,classic_bike,2026-01-15 14:25:42.526,2026-01-15 14:33:18.854,Shore Dr & 55th St,CHI00394,Woodlawn Ave & 55th St,CHI00423,41.795212,-87.580715,41.795264,-87.596471,casual
11,11,DE49E58F9EE6DEDC,classic_bike,2026-01-05 09:03:16.109,2026-01-05 09:05:14.104,Sacramento Ave & Lyndale St,CHI02126,California Ave & Milwaukee Ave,CHI00307,41.922350,-87.702410,41.922695,-87.697153,member
13,13,92A6DFB8B316D899,classic_bike,2026-01-01 15:55:46.488,2026-01-01 15:57:12.972,Sacramento Ave & Lyndale St,CHI02126,California Ave & Milwaukee Ave,CHI00307,41.922350,-87.702410,41.922695,-87.697153,member
14,14,C55845D8689A8FBF,classic_bike,2026-01-09 08:50:22.379,2026-01-09 08:51:53.716,Sacramento Ave & Lyndale St,CHI02126,California Ave & Milwaukee Ave,CHI00307,41.922350,-87.702410,41.922695,-87.697153,member

In [47]:
# Creating copy of the dataframe to add new column:
df_ridet = no_nan_no_test_data.copy(deep=True)

# Adding new column with ride time:
df_ridet.insert(
    loc=4, column='ride_t[s]', value=df_ridet['ended_at'] - df_ridet['started_at'])
# Changing ride time to seconds:
df_ridet['ride_t[s]'] = df_ridet['ride_t[s]'].astype('timedelta64[s]')

df_ridet.head(5)

,index,ride_id,rideable_type,started_at,ride_t[s],ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0,FD0EB1D32AF0D47E,classic_bike,2026-01-31 09:13:09.018,0 days 00:15:01,2026-01-31 09:28:10.302,Central St & Girard Ave,CHI02042,Dodge Ave & Church St,CHI00741,42.064313,-87.686152,42.048308,-87.698224,member
1,1,FB27405C3F8C824F,classic_bike,2026-01-15 14:25:42.526,0 days 00:07:36,2026-01-15 14:33:18.854,Shore Dr & 55th St,CHI00394,Woodlawn Ave & 55th St,CHI00423,41.795212,-87.580715,41.795264,-87.596471,casual
11,11,DE49E58F9EE6DEDC,classic_bike,2026-01-05 09:03:16.109,0 days 00:01:57,2026-01-05 09:05:14.104,Sacramento Ave & Lyndale St,CHI02126,California Ave & Milwaukee Ave,CHI00307,41.922350,-87.702410,41.922695,-87.697153,member
13,13,92A6DFB8B316D899,classic_bike,2026-01-01 15:55:46.488,0 days 00:01:26,2026-01-01 15:57:12.972,Sacramento Ave & Lyndale St,CHI02126,California Ave & Milwaukee Ave,CHI00307,41.922350,-87.702410,41.922695,-87.697153,member
14,14,C55845D8689A8FBF,classic_bike,2026-01-09 08:50:22.379,0 days 00:01:31,2026-01-09 08:51:53.716,Sacramento Ave & Lyndale St,CHI02126,California Ave & Milwaukee Ave,CHI00307,41.922350,-87.702410,41.922695,-87.697153,member

In [ ]:
#All time values were calculated into seconds for further analysis.

#Checking for negative and irrelevant ride times:
#Negative ride time value means an input error which 
#should not be considered. For the analysis purpose 
#also the ride time below 60 seconds won’t be taken into account.

In [49]:
# Sorting data by ride time:
df_rt_sorted = df_ridet.sort_values(by='ride_t[s]')

df_rt_sorted.head(10)

,index,ride_id,rideable_type,started_at,ride_t[s],ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
352004,12767,36BF909589CB87C7,electric_bike,2026-03-30 07:37:31.465,0 days,2026-03-30 07:37:32.441,N Carpenter St & W Lake St,CHI00808,N Carpenter St & W Lake St,CHI00808,41.885586,-87.653189,41.885586,-87.653189,member
74165,74165,39C3FC4ED6085E51,electric_bike,2026-01-09 09:10:42.899,0 days,2026-01-09 09:10:43.131,Sacramento Blvd & Fulton Ave,CHI00902,Sacramento Blvd & Fulton Ave,CHI00902,41.886528,-87.701670,41.886528,-87.701670,member
353846,14609,65BB86BDF3038105,electric_bike,2026-03-10 08:12:34.473,0 days,2026-03-10 08:12:35.452,Sheffield Ave & Armitage Ave Public Rack,CHI00836,Sheffield Ave & Armitage Ave Public Rack,CHI00836,41.917848,-87.653325,41.917805,-87.653449,member
186112,48325,8A56A7667177C9A7,electric_bike,2026-02-18 13:06:59.840,0 days,2026-02-18 13:07:00.824,Albany Ave & Belmont Ave,CHI00924,Albany Ave & Belmont Ave,CHI00924,41.939638,-87.705263,41.939638,-87.705263,member
67634,67634,EBACD24694D0BAD8,electric_bike,2026-01-05 18:06:33.917,0 days,2026-01-05 18:06:34.058,Public Rack - Hollywood Park,CHI01734,Public Rack - Hollywood Park,CHI01734,41.989290,-87.711820,41.989290,-87.711820,member
412912,73675,C5C646A10184C99D,electric_bike,2026-03-30 17:49:21.628,0 days,2026-03-30 17:49:22.371,Whipple St & Roosevelt Rd,CHI00913,Whipple St & Roosevelt Rd,CHI00913,41.866554,-87.701329,41.866554,-87.701329,casual
193087,55300,63CF297CCF189B8E,electric_bike,2026-02-27 16:01:16.264,0 days,2026-02-27 16:01:17.085,Albany Ave & Belmont Ave,CHI00924,Albany Ave & Belmont Ave,CHI00924,41.939638,-87.705263,41.939638,-87.705263,member
548118,208881,3AA68E0B80AF586D,electric_bike,2026-03-01 10:19:07.684,0 days,2026-03-01 10:19:08.120,Public Rack - Bryn Mawr Ave & Spaulding Ave,CHI01610,Public Rack - Bryn Mawr Ave & Spaulding Ave,CHI01610,41.983093,-87.711585,41.983093,-87.711585,casual
336731,198944,C1502FA86CE3FF5E,electric_bike,2026-02-16 19:37:19.630,0 days,2026-02-16 19:37:20.480,Woodlawn & 103rd,CHI00837,Woodlawn & 103rd,CHI00837,41.707388,-87.594039,41.707338,-87.593990,casual
398331,59094,F68BC1D6AEEEC43D,electric_bike,2026-03-29 19:02:49.451,0 days,2026-03-29 19:02:50.054,Eddy/Seminary Corral,CHI02065,Eddy/Seminary Corral,CHI02065,41.946128,-87.656672,41.946128,-87.656672,casual

In [54]:
# Checking for negative ride time values:
from datetime import timedelta
td_zero = timedelta('ride_t[s]'==0)
df_rt_sorted[df_rt_sorted['ride_t[s]'] < td_zero]
df_rt_sorted[df_rt_sorted['started_at'] > df_rt_sorted['ended_at']]

# 71 wrong inputs with negative ride times. Deleting:
df_rt_no_neg = df_rt_sorted[df_rt_sorted['ride_t[s]'] > td_zero]

df_rt_no_neg.head(5)

,index,ride_id,rideable_type,started_at,ride_t[s],ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
11585,11585,65EAA43961B0A1FD,electric_bike,2026-01-05 21:21:46.928,0 days 00:00:01,2026-01-05 21:21:48.751,Central Park & Augusta Blvd,CHI00510,Central Park & Augusta Blvd,CHI00510,41.898911,-87.716490,41.898911,-87.716490,casual
220684,82897,FB1C06E1AE47582F,electric_bike,2026-02-04 07:21:08.659,0 days 00:00:01,2026-02-04 07:21:10.043,Canal St & Madison St,CHI00498,Canal St & Madison St,CHI00498,41.882409,-87.639767,41.882409,-87.639767,member
175620,37833,860067603B3ED710,electric_bike,2026-02-27 21:14:56.526,0 days 00:00:01,2026-02-27 21:14:57.881,Woodlawn Ave & 55th St,CHI00423,Woodlawn Ave & 55th St,CHI00423,41.795264,-87.596471,41.795264,-87.596471,casual
221115,83328,B807E2C56FAA4B1C,electric_bike,2026-02-10 15:23:14.338,0 days 00:00:01,2026-02-10 15:23:16.257,Troy St & Jackson Blvd,CHI00904,Troy St & Jackson Blvd,CHI00904,41.877505,-87.704850,41.877505,-87.704850,casual
398332,59095,12289C1E5E65231E,electric_bike,2026-03-29 19:02:12.281,0 days 00:00:01,2026-03-29 19:02:13.952,Eddy/Seminary Corral,CHI02065,Eddy/Seminary Corral,CHI02065,41.946128,-87.656672,41.946128,-87.656672,casual

In [56]:
td_sixty = timedelta('ride_t[s]'==60)
# Checking for the low ride time values, assuming these are incorrect or irrelevant records (below 60s):
df_rt_no_neg[df_rt_no_neg['ride_t[s]'] < td_sixty]
# There are 73439 inputs with ride time below 60s. Deleting:
df_rt_cleaned = df_rt_sorted[df_rt_sorted['ride_t[s]'] >= td_sixty]
df_rt_cleaned.head(5)

,index,ride_id,rideable_type,started_at,ride_t[s],ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
352004,12767,36BF909589CB87C7,electric_bike,2026-03-30 07:37:31.465,0 days,2026-03-30 07:37:32.441,N Carpenter St & W Lake St,CHI00808,N Carpenter St & W Lake St,CHI00808,41.885586,-87.653189,41.885586,-87.653189,member
74165,74165,39C3FC4ED6085E51,electric_bike,2026-01-09 09:10:42.899,0 days,2026-01-09 09:10:43.131,Sacramento Blvd & Fulton Ave,CHI00902,Sacramento Blvd & Fulton Ave,CHI00902,41.886528,-87.701670,41.886528,-87.701670,member
353846,14609,65BB86BDF3038105,electric_bike,2026-03-10 08:12:34.473,0 days,2026-03-10 08:12:35.452,Sheffield Ave & Armitage Ave Public Rack,CHI00836,Sheffield Ave & Armitage Ave Public Rack,CHI00836,41.917848,-87.653325,41.917805,-87.653449,member
186112,48325,8A56A7667177C9A7,electric_bike,2026-02-18 13:06:59.840,0 days,2026-02-18 13:07:00.824,Albany Ave & Belmont Ave,CHI00924,Albany Ave & Belmont Ave,CHI00924,41.939638,-87.705263,41.939638,-87.705263,member
67634,67634,EBACD24694D0BAD8,electric_bike,2026-01-05 18:06:33.917,0 days,2026-01-05 18:06:34.058,Public Rack - Hollywood Park,CHI01734,Public Rack - Hollywood Park,CHI01734,41.989290,-87.711820,41.989290,-87.711820,member

In [57]:
# Data sorted by date:
df_sort_date = df_rt_cleaned.sort_values(by="started_at")
df_sort_date.head(5)

,index,ride_id,rideable_type,started_at,ride_t[s],ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
39256,39256,493E984B2153C099,classic_bike,2025-12-31 10:30:49.482,0 days 14:26:57,2026-01-01 00:57:46.690,Broadway & Barry Ave,CHI00390,Southport Ave & Wellington Ave,CHI00236,41.937582,-87.644098,41.935775,-87.663600,casual
50680,50680,B8BFADD84C3D48DA,classic_bike,2025-12-31 18:36:46.830,0 days 20:31:21,2026-01-01 15:08:08.579,Morgan St & 18th St,CHI00479,Archer Ave & Wentworth Ave,CHI02006,41.858086,-87.651073,41.854687,-87.630853,member
18778,18778,3B3D79D89BF2F492,classic_bike,2025-12-31 19:49:01.401,0 days 19:19:07,2026-01-01 15:08:08.579,Calumet Ave & 18th St,CHI02039,Archer Ave & Wentworth Ave,CHI02006,41.857618,-87.619411,41.854687,-87.630853,member
12038,12038,BB94A18BA0462AC5,classic_bike,2025-12-31 23:31:12.103,0 days 02:55:11,2026-01-01 02:26:23.361,Canal St & Madison St,CHI00498,Sedgwick St & Schiller St,CHI00303,41.882409,-87.639767,41.907626,-87.638566,casual
1610,1610,024231BAC90568CA,classic_bike,2025-12-31 23:36:22.998,0 days 01:02:47,2026-01-01 00:39:10.110,DuSable Lake Shore Dr & North Blvd,CHI00525,DuSable Lake Shore Dr & North Blvd,CHI00525,41.911722,-87.626804,41.911722,-87.626804,casual

In [59]:
# Deleting irrelevant columns such as ride id’s, station id’s and station coordinates:
# For the analysis purposes ride id's, station id's and coordinates are irrelevant.
df_sort_date.columns

Index(['index', 'ride_id', 'rideable_type', 'started_at', 'ride_t[s]',
       'ended_at', 'start_station_name', 'start_station_id',
       'end_station_name', 'end_station_id', 'start_lat', 'start_lng',
       'end_lat', 'end_lng', 'member_casual'],
      dtype='str')

In [61]:
columns_to_drop = ['ride_id', 'start_station_id',
                         'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng']
df_drop_columns = df_sort_date.drop(columns=columns_to_drop)

df_drop_columns.head(5)

,index,rideable_type,started_at,ride_t[s],ended_at,start_station_name,end_station_name,member_casual
39256,39256,classic_bike,2025-12-31 10:30:49.482,0 days 14:26:57,2026-01-01 00:57:46.690,Broadway & Barry Ave,Southport Ave & Wellington Ave,casual
50680,50680,classic_bike,2025-12-31 18:36:46.830,0 days 20:31:21,2026-01-01 15:08:08.579,Morgan St & 18th St,Archer Ave & Wentworth Ave,member
18778,18778,classic_bike,2025-12-31 19:49:01.401,0 days 19:19:07,2026-01-01 15:08:08.579,Calumet Ave & 18th St,Archer Ave & Wentworth Ave,member
12038,12038,classic_bike,2025-12-31 23:31:12.103,0 days 02:55:11,2026-01-01 02:26:23.361,Canal St & Madison St,Sedgwick St & Schiller St,casual
1610,1610,classic_bike,2025-12-31 23:36:22.998,0 days 01:02:47,2026-01-01 00:39:10.110,DuSable Lake Shore Dr & North Blvd,DuSable Lake Shore Dr & North Blvd,casual

In [63]:
## Adding columns with the day of the week that each ride started
# 0 - Monday, 6 - Sunday:
df_drop_columns.insert(loc=4, column='weekday', value=df_ridet['started_at'].dt.weekday)

all_rides = df_drop_columns.copy(deep=True)
all_rides.head(5)

,index,rideable_type,started_at,ride_t[s],weekday,ended_at,start_station_name,end_station_name,member_casual
39256,39256,classic_bike,2025-12-31 10:30:49.482,0 days 14:26:57,2,2026-01-01 00:57:46.690,Broadway & Barry Ave,Southport Ave & Wellington Ave,casual
50680,50680,classic_bike,2025-12-31 18:36:46.830,0 days 20:31:21,2,2026-01-01 15:08:08.579,Morgan St & 18th St,Archer Ave & Wentworth Ave,member
18778,18778,classic_bike,2025-12-31 19:49:01.401,0 days 19:19:07,2,2026-01-01 15:08:08.579,Calumet Ave & 18th St,Archer Ave & Wentworth Ave,member
12038,12038,classic_bike,2025-12-31 23:31:12.103,0 days 02:55:11,2,2026-01-01 02:26:23.361,Canal St & Madison St,Sedgwick St & Schiller St,casual
1610,1610,classic_bike,2025-12-31 23:36:22.998,0 days 01:02:47,2,2026-01-01 00:39:10.110,DuSable Lake Shore Dr & North Blvd,DuSable Lake Shore Dr & North Blvd,casual

In [ ]:
# Creating new column names for cleaned dataset:

In [64]:
new_columns = {'rideable_type': 'BikeType',
               'started_at': 'RideStart',
               'ended_at': 'RideEnd',
               'ride_t[s]': 'RideTime[s]',
               'weekday': 'Weekday',
               'start_station_name': 'StartStation',
               'end_station_name': 'EndStation',
               'member_casual': 'MemberType'
              }

all_rides = all_rides.rename(columns=new_columns)

all_rides.head(5)

,index,BikeType,RideStart,RideTime[s],Weekday,RideEnd,StartStation,EndStation,MemberType
39256,39256,classic_bike,2025-12-31 10:30:49.482,0 days 14:26:57,2,2026-01-01 00:57:46.690,Broadway & Barry Ave,Southport Ave & Wellington Ave,casual
50680,50680,classic_bike,2025-12-31 18:36:46.830,0 days 20:31:21,2,2026-01-01 15:08:08.579,Morgan St & 18th St,Archer Ave & Wentworth Ave,member
18778,18778,classic_bike,2025-12-31 19:49:01.401,0 days 19:19:07,2,2026-01-01 15:08:08.579,Calumet Ave & 18th St,Archer Ave & Wentworth Ave,member
12038,12038,classic_bike,2025-12-31 23:31:12.103,0 days 02:55:11,2,2026-01-01 02:26:23.361,Canal St & Madison St,Sedgwick St & Schiller St,casual
1610,1610,classic_bike,2025-12-31 23:36:22.998,0 days 01:02:47,2,2026-01-01 00:39:10.110,DuSable Lake Shore Dr & North Blvd,DuSable Lake Shore Dr & North Blvd,casual

In [ ]:
# Exporting clean dataset, ready for analysis:

In [71]:
all_rides.to_csv('Cleaned_Data/202601-202603_cleaned_cyclistic.csv')

all_rides_100 = all_rides[:100].copy()
all_rides_100.to_csv('Cleaned_Data/202601-202603_cleaned_cyclistic.csv')